request_types:
  - type: "Money Movement – Inbound"
    subtypes:
      - "Principal"
      - "Interest"
      - "Principal + Interest"
      - "Principal + Interest + Fee"
    required_info:
      - "Transaction date"
      - "Principal amount"
      - "Sender details"
    decision_words:
      - "money movement"
      - "inbound"
      - "principal"
      - "transaction"
  - type: "Adjustment"
    subtypes: []
    required_info:
      - "Adjustment reason"
      - "Adjusted amount"
      - "Reference ID"
    decision_words:
      - "adjust"
      - "received"
      - "amount"